### ISSUE TITLE
Desktop theme doesn appear - Cinnamon

### ISSUE THREAD

**Issue by patriciaa260** [grassmunk/Chicago95#101]
I installed the theme as per the tutorial, but the desktop (panel) theme doesn' appear . Look:

![chicago95themenotworkpanel](https://user-images.githubusercontent.com/58474298/70056121-4dfc5a80-15b1-11ea-8c87-7dcba49c82c7.png)

Cursor, window, icons, controls, etc. Everything is working, unless the panel. 
I can see there's no Cinnamon folder

**Comment by patriciaa260** [comment]
There's not theme for cinnamon?

**Comment by EMH-Mark-I** [comment]
Sorry about that. The theme is primarily for XFCE desktops. There have been requests for MATE, Cinnamon, GNOME and Plasma desktops too. It would take a lot of time and some knowledge of those desktops to make one.

Also bare in mind that XFCE is by far the closest desktop environment to the original Windows 95 desktop since the two share very common classic traits; so it will look a fare deal different elsewhere even if there was support. Different desktop environments might have their own interface guidelines and overall UI/UX paradigms where a theme such as this can send mixed signals or just get in the way.

**Comment by EMH-Mark-I** [comment]
Just a general update, I'm slowly working on the panel theme. It may have to go through a lot of testing before it's finished.

**Comment by EMH-Mark-I** [comment]
We'll have to make a new metacity window manager theme to support metacity-3. Currently the window theme supports only metacity-1. I'm going to hold off on the window manager theme for now and focus with just the Cinnamon desktop.

**Comment by EMH-Mark-I** [comment]
This is resolved with the new release. The theme should be available from Cinnamon.

There is still no metacity-3 window manage theme, but that should occur sometime in the future.
