### ISSUE TITLE
colors don't look right in xfce

### ISSUE THREAD

**Issue by barfin** [grassmunk/Chicago95#105]
![image](https://user-images.githubusercontent.com/37030489/72690057-9c4bc580-3b2d-11ea-82aa-0ddbfd350508.png)

**Comment by EMH-Mark-I** [comment]
Can you run the following command in a terminal?

    cat /proc/version > ~/output.txt & cat ~/.config/gtk-3.0/gtk.css >> ~/output.txt & xfce4-session --version >> ~/output.txt 2>/dev/null

It will output to a text file in your home directory named, "output.txt"

Copy the contents and paste them to here (redact name if present or necessary.) I'll might be able to determine the issue from there.

Thanks

**Comment by barfin** [comment]
> Can you run the following command in a terminal?
> 
> ```
> cat /proc/version > ~/output.txt & cat ~/.config/gtk-3.0/gtk.css >> ~/output.txt & xfce4-session --version >> ~/output.txt 2>/dev/null
> ```
> 
> It will output to a text file in your home directory named, "output.txt"
> 
> Copy the contents and paste them to here (redact name if present or necessary.) I'll might be able to determine the issue from there.
> 
> Thanks

Linux version 5.4.12-23linux-tkg-pds-haswell (linux-tkg-pds-haswell@archlinux) (gcc version 9.2.0 (GCC)) #1 TKG SMP Thu, 16 Jan 2020 20:30:14 +0000
@import 'colors.css';xfce4-session 4.14.1 (Xfce 4.14)

Copyright (c) 2003-2016
	The Xfce development team. All rights reserved.

Please report bugs to <https://bugzilla.xfce.org/>.

**Comment by EMH-Mark-I** [comment]
OK, so it looks like you have a gtk3 theme override enabled, which I suspect is causing this.

- From a file-manager, can you navigate to `~/.config/gtk-3.0/`? (Press Ctrl-h to display hidden files & directories.)

- You should see a file by the name of `gtk.css`. Rename that file to `gtk_bak.css`, then log out and log back in.

That file is importing a custom colour scheme which is overriding the Chicago95 theme (and other gtk3 based themes too if you haven't noticed.) I suspect that this is generated by either a theme editor or is perhaps a default configuration specified by your Arch distribution.

If you also use the KDE desktop, there is a GTK theme editor that will inject the override file. Keep note if this happens again, because I don't know if this is being applied automatically or not.

Please let me know if this resolves the issue.

Thanks

**Comment by barfin** [comment]
> OK, so it looks like you have a gtk3 theme override enabled, which I suspect is causing this.
> 
>     * From a file-manager, can you navigate to `~/.config/gtk-3.0/`? (Press Ctrl-h to display hidden files & directories.)
> 
>     * You should see a file by the name of `gtk.css`. Rename that file to `gtk_bak.css`, then log out and log back in.
> 
> 
> That file is importing a custom colour scheme which is overriding the Chicago95 theme (and other gtk3 based themes too if you haven't noticed.) I suspect that this is generated by either a theme editor or is perhaps a default configuration specified by your Arch distribution.
> 
> If you also use the KDE desktop, there is a GTK theme editor that will inject the override file. Keep note if this happens again, because I don't know if this is being applied automatically or not.
> 
> Please let me know if this resolves the issue.
> 
> Thanks

i used this file here
https://github.com/grassmunk/Chicago95/blob/master/Extras/override/gtk-3.24/gtk.css
and it's got fixed
