### ISSUE TITLE
Start button shrunk

### ISSUE THREAD

**Issue by okanarbik** [grassmunk/Chicago95#107]
The start button shrunk after upgrading to
xfce4-panel/testing,now 4.14.3-1 amd64 [installed,automatic]

Using regular Application Menu with icon from
.themes/Chicago95/misc/Legacy\ GTK3\ start\ buttons/windows.png

![Screenshot_2020-01-23_20-28-58](https://user-images.githubusercontent.com/33345742/73012431-0068d500-3e1f-11ea-82b2-65c3e2391bf5.png)

Icons size is set to automatic. Setting a fixed size restores Start button but stretches others out of proportion.
![Screenshot_2020-01-23_20-36-11](https://user-images.githubusercontent.com/33345742/73012958-07441780-3e20-11ea-95f4-ef725cbe6ac5.png)

**Comment by EMH-Mark-I** [comment]
You don't have to to choose the legacy gtk3 start buttons anymore!

Those were for distributions that used an early GTK3 version of the Whisker Menu. I can't recall which version of Whisker Menu, but I believe it wouldn't allow for modifying the font weight or style.

Meanwhile the traditional Application Menu plugin was just updated from GTK2 to GTK3 in the XFCE 4.14 release. The "`GTK2 start buttons`" was intended for the older version of Application Menu seen in XFCE 4.12.

Now with XFCE 4.14, none of those buttons are needed anymore. You can simply select a button directly from: ".themes/Chicago95/Theme/Chicago95/misc/"

You may have to experiment a little until you can find a size that fits correctly. For Application Menu, the `windows_16x16px.png` icon seems to work best. For Whisker Menu, the regular `windows.png` seems to work best.

Since these are just the icons them self, you will have to give the Application Menu plugin the "Start" button title by typing it in the button title field.

**Comment by okanarbik** [comment]
Thank you very much for the explanation and suggestions, windows_16x16px.png and Start title field does work well for me. Much appreciated!
