### ISSUE TITLE
Weird dark theme

### ISSUE THREAD

**Issue by arcunofox** [grassmunk/Chicago95#108]
Hello! I have followed all steps in the installation instructions and I bumped into an... odd problem. Basically everything looks like its a mix between a dark and light theme. Icons and everything else works. 
![ehh](https://user-images.githubusercontent.com/54588488/74152235-24ddf300-4c0e-11ea-9347-6c25b270f90b.png)

**Comment by EMH-Mark-I** [comment]
Hi @arcunofox; thanks for reporting the issue.

Can you run the following command and paste back here?

    cat /proc/version > ~/output.txt & cat ~/.config/gtk-3.0/gtk.css >> ~/output.txt & xfce4-session --version >> ~/output.txt 2>/dev/null

**Comment by arcunofox** [comment]
```
Linux version 5.5.2-arch1-1 (linux@archlinux) (gcc version 9.2.0 (GCC)) #1 SMP PREEMPT Tue, 04 Feb 2020 18:56:18 +0000
@import 'colors.css';xfce4-session 4.14.1 (Xfce 4.14)

Copyright (c) 2003-2016
	The Xfce development team. All rights reserved.

Please report bugs to <https://bugzilla.xfce.org/>.
```

**Comment by EMH-Mark-I** [comment]
OK, so it looks like you have a gtk3 theme override enabled, which would be causing this.

- From a file-manager, can you navigate to `~/.config/gtk-3.0/`? (Press Ctrl-h to display hidden files & directories.)

- You should see a file by the name of gtk.css. Rename that file to gtk_bak.css, then log out and log back in.

- Optionally, there's also a gtk.css file provided in [Extras/override/gtk-3.24/](https://github.com/grassmunk/Chicago95/tree/master/Extras/override/gtk-3.24) which you can copy into your `~/.config/gtk-3.0/` directory. This only provides a few additional tweaks that couldn't be applied from the theme itself due to applications specifying their own theming; it isn't very important, but something to note.

Currently the file is importing a custom colour scheme at `@import 'colors.css'`; which is overriding the Chicago95 theme (and other gtk3 based themes too if you haven't noticed.) I suspect that this is generated by either a theme editor or is perhaps a default configuration specified by your Arch distribution.

If you also use the KDE desktop, there is a GTK theme editor that will inject the override file. Keep note if this happens again, because I don't know if this is being applied automatically or not.

Please let me know if this resolves the issue.

Thanks

**Comment by arcunofox** [comment]
Hey, that worked! Thank you :)

**Comment by EMH-Mark-I** [comment]
Great!
Its been a common issue of late.
