### ISSUE TITLE
lightdm theme working incorrectly on xfce

### ISSUE THREAD

**Issue by Askmewho** [grassmunk/Chicago95#110]
Hi!! again! love your work!
Ive tried the lightdm login them and it appeas as a network login , not session one... wierd

**Comment by EMH-Mark-I** [comment]
Sorry,

Do you have a way of sharing a picture?

Thanks

**Comment by Askmewho** [comment]
![IMG_20200312_141832](https://user-images.githubusercontent.com/39385643/76547763-7fb47580-646c-11ea-9b89-d5223379c41c.jpg)

I am making a xfce image of raspbian with your theme (you will be credit, also I will paste your github repo). The idea its too add box86 by default and some more addins. Box86 allow to play x86 linux stuff.. wine (x86) stuff its on the todo. I will share you the final video (but there will be several versions)

**Comment by grassmunk** [comment]
That's by design. It's hardcoded to look like the Windows 95 logon screen:

![image](https://user-images.githubusercontent.com/3452173/76550868-0b6bd900-6450-11ea-9de2-669a7e1b5a06.png)

**Comment by Askmewho** [comment]
I didnt remember the logon like that. I mean, it's a network logon, not an user one. Thanks for the clarification! I will reopen it soon.

**Comment by mainframed** [comment]
Windows 95 didn't really have user logins and only really added them for "network"

**Comment by Askmewho** [comment]
@grassmunk 
https://youtu.be/NyaNrY50XCA

**Comment by Askmewho** [comment]
![IMG_20200320_221055](https://user-imag@grassmunk githubusercontent.com/39385643/77216246-c0109500-6af7-11ea-80a6-a6dbd5c30542.jpg)
@grassmunk hi!! Do you know any way to add a logo here on xfce like win95 had??
Also, there is any way to add the win95 sound desktop effects somehow(I know that a bit difficult)

**Comment by EMH-Mark-I** [comment]
I'm not sure how possible it is. I've seen it before from Mathewsmx86's [Redmon97](https://github.com/matthewmx86/Redmond97) theme, but avoided implementing it here since it relies on a static image that doesn't scale properly and could appear stretched or compacted due to the size of the application or whisker menus.

There's no application sound theme with Chicago95. I'm not sure if sound themes are possible with XFCE, but if it is then it might be worth some consideration.

I am aware of sound themes for MATE and other desktop environments, however XFCE is still the primary desktop for Chicago95, even though I've extended some support for Cinnamon and MATE.

**Comment by Askmewho** [comment]
@EMH-Mark-I Understand! I just add an easy intro sound on my image for rpi4, also the maze clone screensaver. While the hunter house may be a good addition (or even the original maze) it doesnt worth the size of the video file (since we dont have a real screensaver for that). Hope you apply the logo thing, even if it had some problems. I mean, there should be a way to make it possible having different logos size for common resolutions. Thanks to this mighty work.

**Comment by grassmunk** [comment]
Just FYI @Askmewho we've now added the side menu to whisker: https://github.com/grassmunk/Chicago95/issues/111
