### ISSUE TITLE
Win2000 gradient color and borders

### ISSUE THREAD

**Issue by DocMAX** [grassmunk/Chicago95#12]
Hello,
everything looks like Win2000, but the borders don't disappear when maximized.
Also i would like to see the original gradient color of the titlebar from the old days...

DocMAX

**Comment by EMH-Mark-I** [comment]
FYI I have an issue ticket opened about GTK3 issues after a recent merged pull request that just nuked a good portion of code, leaving GTK3 applications in a unusable state.

> the borders don't disappear when maximized.

The borders surrounding the entire window of the application or only the top border above the title bar? 

A screen shot might help. Also, does this happen for all applications or just particular ones?

I don't believe it's possible to hide the window border above the title bar for maximized applications, but I'll look at it. I'm aware that it doesn't do this in Windows95, however it might just be a limitation of the XFCE window manager.

> Also i would like to see the original gradient color of the titlebar from the old days...

The gradient colour was implemented in Windows98. The theme is attempting to mimic Windows95 which had a solid blue colour in the title bar. I can look at it and possibly add it as a commented out option in a theme file.

**Comment by DocMAX** [comment]
> The borders surrounding the entire window of the application or only the top border above the title bar?

You're right, only the top border needs to be fixed. It happens for all applications.
Looking forward for a new release!

**Comment by EMH-Mark-I** [comment]
I looked into the colour gradient for the title bar. From what it appears, I'm not sure if this will be possible without making some modifications to the window manager itself, which is beyond me.

From what I'm seeing so far vertical colour gradients are easy enough and you'll see those in other themes, but horizontal gradients not so much. The way the window manager handles the title bar is by using x pix map images. It expects to find a specific defined set of images in the "xfwm4" directory under the theme, and it repeats them one beside the other until it fills the title bar (in other words the title bar you are seeing is made up of multiple smaller images repeated over.) If the pixmap image is made with a horizontal colour gradient, it will cause an odd stepping effect due to the image being repeated.

Thing to note, XFCE is supposed to be a lightweight desktop which means it's going to have limitations in the eyecandy department. I don't think a 1 to 1 replica is going to be feasible, or at least on XFCE. 

I have a fork of the theme you can try out if you run into issues at the moment with GTK3 applications.
