### ISSUE TITLE
Will this theme be affected by the switch to CSD that some DE's (including XFCE) will force on us ?

### ISSUE THREAD

**Issue by Jp0222** [grassmunk/Chicago95#123]
To my understanding it would be a lot more difficult to create and use custom themes when CSD is being enforced.
How will chicago95 be affected by this ?

**Comment by EMH-Mark-I** [comment]
It's going to depend on the application, however there are already decorations for client side decorated GTK3 applications included with the theme, and have been there for quite some time.

Titlebar buttons: Theme/Chicago95/gtk-3.24/gtk-titlebars.css
Titlebar window manager style buttons: Theme/Chicago95/gtk-3.24/gtk-windowbuttons.css
Window decorations: Theme/Chicago95/gtk-3.24/gtk-window.css

You can observe this in applications such as Geary, Feed Reader, Software Centre, and the GNOME disk utility.

Now yes, these don't look like the traditional titlebar you would expect to see from the window manager. If you want to recover the titlebar, then I recommend looking into gtk3-nocsd, or possibly other related projects. I would like to add an option in Extras/ for people using gtk3-nocsd or other applications that enforce the window manager titlebar, so that their CSD applications won't display with a duplicate / extended titlebar and window border effect. I'll have to test with it to see how it looks though.

**Comment by EMH-Mark-I** [comment]
Would like to make one correction. Those file paths for gtk-titlebars.css, gtk-windowbuttons.css, and gtk-window.css are currently only available on the Staging branch. As for the contents of those files, they were originally located in `--/Chicago95/gtk-3.24/gtk-widgets.css`. I've since separated the contents out into individual files so that it would make it easier to work with.

**Comment by EMH-Mark-I** [comment]
This issue is resolved.
