### ISSUE TITLE
Cannot Log In into Desktop

### ISSUE THREAD

**Issue by sapi01** [grassmunk/Chicago95#150]
I installed Chicago95 in a fresh install of `Ubuntu 20.04 LTS(Codename: focal)` when I logged out, I was presented with Chicago95's login screen(which is expected) BUT when I accidently pressed "switch user" on the listed buttons, I was redirected to XFCE's user login screen. I logged in as normal user, BUT here Im struck with Chicago95's Desktop Login. I cannot able to click onto the Text book(for typing password) everything on the textbook was very unresponsive. I had to reboot to login into my Desktop(I was greeted by XFCE's Desktop login screen after reboot). Can someone tell me why this is happening? For making sure, I tested multiple times and everytime I press "switch users", I will be redirected to XFCE's Desktop login screen and I enter correct password for the user and I "again" redirected to Chicago95's Login screen which is where my Password Text book gets struck.

**Comment by EMH-Mark-I** [comment]
Hi @sapi01 
In which way did you install the theme?

- OBS Repository 
- installer.py script
- Manually

Thanks

**Comment by sapi01** [comment]
I manually cloned the repo and did these following commands.
```
mkdir -p ~/.themes
mkdir -p ~/.icons
cp -r Chicago95/Theme/Chicago95/ .themes/
cp -r Chicago95/Icons/* ~/.icons.
```
And then I changed the theme, cursor and other stuff like window icons, fonts from XFCE settings manager.

**Comment by EMH-Mark-I** [comment]
OK, that all looks good. I only ask because I believe the OBS repo may have a customized version of the old webkit greeter which probably won't work on newer versions of Ubuntu, so just trying to make sure you may not of accidentally installed that.

Now I did some testing and was able to reproduce your issue from one of my workstations. It didn't matter which GTK theme was enabled, it is reproducible regardless of the theme. After further troubleshooting I've come to the conclusion that this is occurring due to a race condition caused by running both light-locker and xfce4-screensaver simultaneously. The keyboard is not being properly remapped to the DISPLAY 0 user session due to light-locker.

You should only need one or the other for handling session locking. I recommend opening xfce4-session-settings > Application Autostart. Scroll down the list of items until you find:

- light-locker = Screen Locker (Launch screen locker program)
- xfce4-screensaver = Screensaver (Launch screensaver and locker program)

And remove the check beside the one you don't need then move to the "Saved Sessions" tab and click on "Clear Saved Sessions." Reboot your computer after this.

**Comment by sapi01** [comment]
Works, we can close this issue for now
