### ISSUE TITLE
Plus generator does not generate Cinnamon shell color scheme properly

### ISSUE THREAD

**Issue by zara1193** [grassmunk/Chicago95#161]
As the title says, it seems to just carry over the default Cinnamon shell theme from the base Chicago95 theme, much like the other issue I reported regarding GTK2 color schemes.

**Comment by grassmunk** [comment]
So i looked in to this and I'm not sure why, im not really familiar with Mate theme generation. Could you provide more information what the exact issue is?

**Comment by zara1193** [comment]
Apologies, this is specifically for the Cinnamon desktop and its shell/panel theme (I've been testing the theme under different environments lately just for fun.) I've noticed that much like the problem with GTK2 color generation, the Cinnamon themes are generated based on the stock color scheme of Chicago95 no matter what Microsoft theme file is supplied.

**Comment by grassmunk** [comment]
Does this get fixed if the gtkrc file is edited?

**Comment by zara1193** [comment]
> Does this get fixed if the gtk2.0/gtkrc file is edited?

It doesn't, unfortunately. This error seems to occur in the Plus script while the theme is being generated regardless of gtkrc values.

**Comment by ObdS7** [comment]
automatic setup? in lubuntu..

**Comment by ObdS7** [comment]
more lite envoriment? lxde no xfce

**Comment by EMH-Mark-I** [comment]
The Cinnamon shell theme is separate from the rest of the GTK theme. See: https://github.com/grassmunk/Chicago95/blob/master/Theme/Chicago95/cinnamon/cinnamon.css

I don't believe the Cinnamon shell is capable of CSS variables, and it doesn't share the same "@define-color" @ rules functionality seen in the GTK toolkit; heck, I don't think it even supported a way to import additional .css files either. Back when I made that theme I tried everything to make that work, but was unsuccessful. This prevents the ability for the Plus theme generator to work for the Cinnamon shell theme because each color value has to be individually, tediously, specified through that file.

The way the Plus theme generator works is by parsing the gtk.css files and switching specific values based on what was sampled from the imported .plus theme. It will also convert some color values of static images too, but is limited to only the GTK3 theme.

Support for MATE and Cinnamon desktops is only partially there as only the basic default GTK theme. The extra features and functionality are primarily present for the XFCE desktop.

**Comment by zara1193** [comment]
> The Cinnamon shell theme is separate from the rest of the GTK theme. See: https://github.com/grassmunk/Chicago95/blob/master/Theme/Chicago95/cinnamon/cinnamon.css
> 
> I don't believe the Cinnamon shell is capable of CSS variables, and it doesn't share the same "@define-color" @ rules functionality seen in the GTK toolkit; heck, I don't think it even supported a way to import additional .css files either. Back when I made that theme I tried everything to make that work, but was unsuccessful. This prevents the ability for the Plus theme generator to work for the Cinnamon shell theme because each color value has to be individually, tediously, specified through that file.
> 
> The way the Plus theme generator works is by parsing the gtk.css files and switching specific values based on what was sampled from the imported .plus theme. It will also convert some color values of static images too, but is limited to only the GTK3 theme.
> 
> Support for MATE and Cinnamon desktops is only partially there as only the basic default GTK theme. The extra features and functionality are primarily present for the XFCE desktop.

Thank you for the very detailed explanation. Since you're well aware of how and why this issue is occurring, it's probably safe to close this for now since Cinnamon & MATE aren't the targetted platforms, but I found it worth mentioning anyway just in case future support for those environments is an interest sometime down the road!
