### ISSUE TITLE
Toolbar broken in Libreoffice 5.4, Xubuntu 16.04.3 LTS

### ISSUE THREAD

**Issue by mknepper** [grassmunk/Chicago95#18]
As you can see, it's pretty broken:

![brokentoolbars](https://user-images.githubusercontent.com/12740958/29745723-78e1c58e-8a88-11e7-93e9-cf9cd68141c6.png)

Another FYI. Probably something to do with a GTK revision.

**Comment by paolodina** [comment]
same here

**Comment by EMH-Mark-I** [comment]
Oof this is old. Sorry nobody helped! :(

Unfortunately this version of the theme targets GTK3.22, which isn't ported to Ubuntu 16.04 (currently running GTK3.18.) So ideally you would have the theme on Ubuntu 17.04 or 17.10.

Since I also run on 16.04 [I've kept a custom version](https://github.com/EMH-Mark-I/Chicago95-Custom-XUbuntu-16.04-) of the theme that works quite well. However It'll require running gtk3-nocsd which will disable the client side decorations by relegating them to a toolbar instead of the titlebar. Just letting you know in case that's a deal breaker.
