### ISSUE TITLE
Font misplaced/missized in LibreOffice drop-down menus

### ISSUE THREAD

**Issue by 3rd3** [grassmunk/Chicago95#186]
![grafik](https://user-images.githubusercontent.com/2372391/116519445-c879f880-a8d1-11eb-9f4d-d3582e8e5016.png)

**Comment by EMH-Mark-I** [comment]
This is peculiar. After some commits since April 29’th, I think this might now be addressed? I can’t be for certain, but I’m not seeing this in my Libre Office Writer.
If you’re still experiencing this issue, then let me know, as well as what OS and version you are running and perhaps the version of Libre Office as well.
Thank-you

**Comment by 3rd3** [comment]
This seems to have been fixed in the current master branch.
