### ISSUE TITLE
GPL infringement  by TwisterOS

### ISSUE THREAD

**Issue by neofeo** [grassmunk/Chicago95#203]
This guys are on infringement of your GPLs on this work

[Twisteros](www.twisteros.com) 

The build is also available as an script for x86_64  pcs.

They don't have a repo,  they just made a custom image based on your work and others and they are not publishing anything.

I know you are not willing to do anything  about it. But just to let you know.

**Comment by Kippykip** [comment]
I mean I've got a custom made image too, but it links to the project and extensively credits it during the install:
https://kippykip.com/index.php?threads/releases-winedows-linux-distribution-thread.1661/

although honestly GPL infringement would be the last thing on my mind considering how much copyright infringement this project is doing itself

**Comment by neofeo** [comment]
Well, they aren't any links on his site to this github repo, neither all the other works they had stolen. 

Off-topic: I don't care that much about ancient MS rights to the logos/icons.  I think that's abusive, the same way that's abusive that this guys not even mention all the other work involved here by others people neither sharing his changes (bc they had made custom icons too)

They don't have any repo for those changes, and even licensed the theme switcher (with unknown terms about it). They do not take and share. They just took, and they do not share anything. And if it's okay to make closed source stuff around open source works like the this one by grassmunk, then I am not okay at all.

**Comment by EMH-Mark-I** [comment]
I’m only one of the contributors of the project, so others are welcome to chime in if they would like.

For simply CSS theme files, I can’t find the motivation to get up in arms over alleged infringements here. It’s all just a form of script after all, which was made up by examples observed from other GTK themes. Besides, the Chicago95 theme isn’t exactly legal eagle itself due to the icon set and MS branded assets, so it would make quite an embarrassing display of the pot calling the kettle black.

Now I will warn, including the Chicago95 project into a distributed product such as Twitteros or in other projects could be a liability for those maintainers, and I highly recommend for their sake to exclude at least the icon theme and any logo depicting images, or else they could potentially face a “Lindows” situation with Microsoft.

Thank you!
