### ISSUE TITLE
Some title bars not scaling correctly

### ISSUE THREAD

**Issue by Whatscheiser** [grassmunk/Chicago95#212]
Hello, I have an image here to illustrate. I'm running Linux Mint XFCE 20.2 XFCE version is 4.16  ...I also have a machine with Mint 20.1 that doesn't seem to encounter this problem, but I'm not really sure why...
![image](https://user-images.githubusercontent.com/90274289/146267761-11632daa-d69d-4407-a38c-b584b738ca7d.png)

Please let me know if there is anything I can do on my end to resolve. Thanks.

**Comment by Whatscheiser** [comment]
So I've since come across a project with a script that automates a bit more of this installation here: [https://github.com/dominichayesferen/Chicagofier](url) 

There is settings that are modified from this script that fixes the issue. This script is doing quite a bit though. At some point I'll have to sift through it and figure out which thing it is that resolves the problem. But in the meantime, for me running Mint 20.2 the fix is to install with that script.

Of course this script does break a thing too. LOL. I was able to get to the bottom of that issue though. The message dialog boxes would end up with a double-chin effect. It looks like the highlight and shadow art that gets applied around the border of a window frame ends up being applied twice and visibly not lined up with each other. 

This can be resolved by going into ~.Themes/Chicago95/ gtk-3.0 ... Open gtk.css and remove the following line near the bottom of the file   ----   "@ import url("gtk-messagedialog.css");"

Now it appears everything is fully working.

**Comment by qsmodo** [comment]
Can we open this issue? I believe it's still relevant.

**Comment by Whatscheiser** [comment]
Sure, but I'd reiterate that if you are having the issue the Chicagofier script seems to work well for a resolution. Just keep in mind the edit that needs to be made to gtk.css

But I suppose it would be nice to get a word from someone who has a better handle on why that may be.

**Comment by EMH-Mark-I** [comment]
Could you include a screenshot of what you're expecting to see? I suspect this might have to do with XFCE 4.16, which has moved to a CSD titlebar for all XFCE applications.
Thanks!

**Comment by qsmodo** [comment]
I cannot access my system with XFCE right now, but I'd expect the height of the titlebar to become smaller, so that the close/max/min buttons fit perfectly inside, just like with other common programs such as Xterm.

Now, in the provided screenshot, it looks like the settings icon and the find button may be what's forcing the titlebar to become larger. If they could be shrunk, perhaps the titlebar would automatically fall back to the default height.

**Comment by EMH-Mark-I** [comment]
This clears it up, thanks.
There's documentation on how to recover the original XFCE application styles in the readme, but it's easy to overlook.
As of XFCE 4.16, the project has decided to adopt the GNOME style Client Side Decorations in place of the typical XFWM window manager title bar and window controls for nearly all of their applications. This is how the title bar is supposed to look.

A GTK theme can only change the appearance of things without altering the functionality of the application; and there are limits to that as well. I tried to make the CSD title bar theme as small as possible, but the application icon space is a static size that the theme is not able to override.

I'm also not sure if it is possible to position the control buttons (close, restore, minimize). From what I've seen of other themes, precise positioning seems to be the norm, which is certainly poor usability.

----

To restore the XFCE applications back to normal, read "[Disabling GNOME Client Side Decorations](https://github.com/grassmunk/Chicago95/blob/master/INSTALL.md#nocsd)" in the README. It covers on how to do this, which is what I expect this script you're running is performing for you.

**Comment by EMH-Mark-I** [comment]
Well the main reason the install script doesn't automate some of this is because the theme is multi-platform. Each Linux based distribution may have a slight alteration in XFCE or GTK version.

For example, XUbuntu 18.04 comes with XFCE 4..12. XUbuntu 20.04 comes with XFCE 4.14. And XUbuntu 22.04 will come with XFCE 4.16. I can't remember off hand which version of GTK3+ is also included, but each release of XUbuntu has a different version of GTK as well.

For non Ubuntu derivatives, let's say Debian, Devuan, Arch, etc; the XFCE and GTK versions can vary by a lot.

I try to keep the theme as cross platform as possible, but it might not always look the same depending on font DPI settings, display compositor used (or a lack thereof). I also strive to support some of MATE and Cinnamon desktop environments too, which also have various versions.

The install-able `libxfce4ui-nocsd` package is only for XFCE 4.16, and may not be available in some distribution package archives. It would be difficult to write out a script and maintain it to where it would work across a variety of platforms as well. So for the more advanced things like this, I prefer to just direct people to the documentation if they're so inclined.

I might someday soon write a comprehensive picture guide on my website for the theme, but it would be heavily Debian biased since it's the only platform I'm most familiar with.

If you have any recommendations that could be made to the current documentation, then I'm all ears; especially from Arch users, since I'm not familiar with that platform.

I can be reached via XMPP at EMH_Mark_I@mail.emhmki.org, or my IRC server. Connection details are on the site (click GitHub profile for link.)

Thank-you

**Comment by Whatscheiser** [comment]
Hey thanks again for the detailed reply it's much appreciated. Pictures do help, LOL. I can get my way around Linux and can generally google my way out of a problem. Slowly but surely that knowledge gained in bits and pieces is starting to accumulate but an expert, I am not. So for someone like me a document with images showing a wrong configuration with some detail for a resolution to the problems shown would be helpful. For example, a picture of that title bar I posted at the top of the thread with some flavor text like "if you see this then check that" with _that_ referring to the docs you were kind enough to point me to. Or even the explanation you gave here would be great. That would basically read to my caveman brain as "STOP HERE LOOK AT THIS". Which at times I'll admit, I do need.

Again, thanks for the responses here. I'd say this is pretty thoroughly answered and I appreciate your time. I'll go ahead and close this out.
