### ISSUE TITLE
Can't find installer.py

### ISSUE THREAD

**Issue by mattdimicelli** [grassmunk/Chicago95#225]
Sorry for the newbie question.

I downloaded and installed the repository from https://software.opensuse.org//download.html?project=home%3Abgstack15%3AChicago95&package=chicago95-theme-all and installed as per the instructions for Ubuntu 20.04.

After doing so I was able to find a program called Chicago95 Plus!, which I couldn't get to do anything (it seems like I need a theme).

I tried to follow the rest of the manual install and setup instructions (specifically "Single user automated install") , however I cannot find the mentioned installer.py file anywhere.

I realize that this file is included in the git repository but I shouldn't be cloning the repo because I already installed Chicago95 via the command line... right?

Please clarify the install instructions.  Thank you!

**Comment by EMH-Mark-I** [comment]
Hi @mattdimicelli

I've looked at the Chicago95 Plus! issue from the OBS package install and found that there are a few issues. Primarily, it isn't working because of a file permission issue with `/usr/libexec/chicago95-theme-plus/`.

A `chmod -R 777` on that specific directory would fix it (if you're familiar with adjusting file permissions), but I'll work with addressing it with the package maintainer.

----

When you download the Chicago95 .tar.gz from GitHub, then extract it, the install.py file would be located in the extracted `Chicgao95-master` directory.

![Screenshot_2022-02-26_12-44-28](https://user-images.githubusercontent.com/28378002/155855409-37e08f33-25f0-4295-a3f0-fd1cb11d5903.png)

And if you cloned the git repo, then it should still be there as well. You shouldn't have to clone the repo though, unless you want to contribute or work with the project. It's a tool for development, so you don't have to use it. You can simply download the source material.

![Screenshot from 2022-02-26 12-50-41](https://user-images.githubusercontent.com/28378002/155855569-465b0ee1-525a-4331-bd95-2ddfe5970b87.png)

Git-Hub can be a little tricky to learn at first, and really wasn't intended as a software distribution front-end for non-developers, so my apologies for the confusion.

**Comment by mattdimicelli** [comment]
Hi EHM-Mark-I.  Thank you so very much for your detailed and illustrated explanation!  

I think for newbs like me there might be a bit of confusion regarding the OBS package, because at least I thought that downloading that alone was all that was necessary.  I didn't realize that it was a different application than what is in Chicago95 .tar.gz .

Thanks once again!
