### ISSUE TITLE
Start menu not changing like screenshot in XFCE

### ISSUE THREAD

**Issue by revix-0** [grassmunk/Chicago95#226]
the theme has been installed correctly, colors, icons, windows ecc, but the start menu appears like the normal default linux one, also i don't have the boot startup animation of windows 95, the screensaver login screen didn't changed as well

**Comment by EMH-Mark-I** [comment]
Well some of those things will require some manual installation. If you ran only the install script or installed by the OBS repo, then that will certainly be the case.
We haven't exactly perfected an install script method because different distributions will have different requirements.

- Here are the steps for installing the [Plymouth boot up-theme](https://github.com/grassmunk/Chicago95/blob/master/Plymouth). (Note: If you're running an Nvidia graphics card, I don't believe Plymouth boot themes work. You'd probably just see a blank screen until you can login. I'm not sure if that's still the case or not.)

- The login screen (the lightdm-wbkit login theme) no longer works since the package is deprecated in modern distributions. However, it's possible to enable the GTK theme for the login screen but I never wrote instructions for it in the documentation. I'll work on some steps for that, but it involves manually installing the theme in `/usr/share/themes/`, then installing the `lightdm-gtk-greeter-settings` package, then open that program "LightDM GTK+ Greeting settings," and changing the "Theme" option to Chicago95. You may have to reboot after applying.

- The start menu I am assuming is the Whisker menu? You'll also have to manually adjust that too in the Whisker setting panel. If you ran the install script, it would of opened a text file with a few follow up steps to take. I'll paste them here below.

        Open the XFCE settings manager > Panel > Items tab > Double click the Whisker / Application menu item in the item list; alternatively you can also access their settings menu by right clicking the icon from the panelbar and selecting "properties."

        - In the Whisker / Application properties menu click the icon option (*This will appear as the icon badge on your start button that's currently in use.*)
        - In the "Select An Icon" window, navigate to `/home/$USER/.themes/Chicago95/misc` (*with $USER being your username.*) You may have to click the pull-down menu from "Select icon from" and then select "Image Files" so that you can navigate to a custom icon on your filesystem. You may also have to enable the filechooser to display hidden files. (*Press Ctrl+h to toggle this setting.*)

        `misc/` contains simple small icon badges in different sizes. You may have to experiment a little until you can find a size that fits correctly
    
        ....`misc/GTK2 start buttons/` contains start buttons that are used for the GTK2 version of the Whisker / Application Menu plugin.
    
        ....`misc/Legacy GTK3 start buttons/` contains start buttons that were used for an older GTK3 version of the Whisker / Application Menu plugin.
    
        *Note: The smallest optimal panel row size for this theme is 24 pixels. If your panel is below that size, you will encounter icon scaling issues.*

I hope this helps.

**Comment by revix-0** [comment]
i see, as for the blue bar color in the window manager settings, where can i find it's color parameter? i want to apply the gradient to it like i've done with the bar below
![image](https://user-images.githubusercontent.com/30447649/155860506-1ba331b3-3224-450f-a53b-c576fb9dd268.png)

**Comment by EMH-Mark-I** [comment]
I see that. You'll have to change the Whisker Menu settings too. If you right-click on the "Start" button (Whisker Menu), select Properties from the menu.

From the Whisker Menu properties window, you can change the layout. This is how I keep mine set:

![Screenshot_2022-02-27_09-26-38](https://user-images.githubusercontent.com/28378002/155888703-8cda06d6-e511-4ef6-8278-054555a11f23.png)

Different versions of the Whisker Menu plugin will have different options. This is mine from the XUbuntu 20.04 distribution.

**Comment by CrashOveride95** [comment]
> * Here are the steps for installing the [Plymouth boot up-theme](https://github.com/grassmunk/Chicago95/blob/master/Plymouth). (Note: If you're running an Nvidia graphics card, I don't believe Plymouth boot themes work. You'd probably just see a blank screen until you can login. I'm not sure if that's still the case or not.)

For the record, on my nvidia card (with official driver) the bootup screen works as expected

**Comment by Sir-Photch** [comment]
>     * The login screen (the lightdm-wbkit login theme) no longer works since the package is deprecated in modern distributions. However, it's possible to enable the GTK theme for the login screen but I never wrote instructions for it in the documentation. I'll work on some steps for that, but it involves manually installing the theme in `/usr/share/themes/`, then installing the `lightdm-gtk-greeter-settings` package, then open that program "LightDM GTK+ Greeting settings," and changing the "Theme" option to Chicago95. You may have to reboot after applying.

I suggest adding that to the installation-instructions, since that worked for me.

**Comment by Dan4096** [comment]
> 

Would you mind writing some instructions please to setup the login screen to match the screenshots?
Thanks for your efforts on this entire project, by the way, it's fantastic!
