### ISSUE TITLE
Title bar elements are misplaced

### ISSUE THREAD

**Issue by 0x5066** [grassmunk/Chicago95#234]
![image](https://user-images.githubusercontent.com/38136789/160916713-8d1ed228-ad0a-4d5e-86a7-e99909117b4d.png)

After issue #223 was addressed and today the AUR got the latest git from Chicago95, I immediately noticed something was off, compare the two title bars and you'll notice the elements on the title bar at the bottom are off, I put some red lines there to illustrate the difference

**Comment by EMH-Mark-I** [comment]
I've adjusted the button offset to address this. 

Now I hope that this won't cause a usability issue. I initially made some changes here at one point for the window manager theme so that you could run the pointer to the upper-most right corner and click to easily close a window without having to reposition it.
