### ISSUE TITLE
My Terminal Appearence doesn't look like yours

### ISSUE THREAD

**Issue by khalidalwalid** [grassmunk/Chicago95#245]
Hi, 
I have just installed Chicago 95 theme on my XFCE with the spesification below:
OS: Kali GNU/Linux Rolling x86_64 2022.2
DE: Xfce 4.16
Shell: zsh 5.8.1
GTK version: 3.24.33
Terminal: Qterminal

I have installed this theme by automatic installation and everything is fine. But, when it finished, my terminal appearance just changed a little, and it didn't look like your terminal in this screenshot.
![Desktop1](https://user-images.githubusercontent.com/33023197/174471028-bc9d3c74-f0f0-4235-b037-fc55da6ccb76.png)

And this is my terminal appearance.
![myterminal](https://user-images.githubusercontent.com/33023197/174471048-d6f9311d-8894-4cfa-8257-075ca4132afa.png)

Why is it? And what should I do?

Anyway, thanks for the theme, and also thanks for helping me.

**Comment by Kippykip** [comment]
I think you need to use the XFCE4 terminal, that looks like something different?

**Comment by EMH-Mark-I** [comment]
The Qterminal application uses a different toolkit (Qt) while this theme project is primarily focused for GTK applications. The screenshot of the terminal is the xfce4-terminal, which is often the default for XFCE desktops. It's a GTK based terminal emulator, whereas Qterminal is Qt based.

There is a section in the documentation on how to enable a similarly appearing Windows95 like theme for Qt based applications. It also includes a color profile so that your Qt applications should look some-what similar, but there will be some noticeable differences.

I recommend reading the following:

[Enabling the theme for QT5 applications (optional)](https://github.com/grassmunk/Chicago95/blob/master/INSTALL.md#enabling-the-theme-for-qt5-applications-optional)
[QT5 theme configration with qt5ct](https://github.com/grassmunk/Chicago95/blob/master/INSTALL.md#-qt5-theme-configration-with-qt5ct--advanced)

These are a little advanced however, requiring some understanding of terminal commands. The instructions are primarily written from the Debian perspective of Linux distributions since they are the only systems I am familiar with, however other distributions may share in some similarities.
