### ISSUE TITLE
[Request] Xfce4 Panel Separator Theming

### ISSUE THREAD

**Issue by SaiTheCyclone** [grassmunk/Chicago95#266]
Would it be possible to include (or have the user add manually) a panel separator theme? It would replace the current panel separator theme with this:
![Screenshot_2022-10-07_17-52-17](https://user-images.githubusercontent.com/61062544/194668068-213d92c0-3c62-4454-b40a-238e1a1fdf54.png)

**Comment by EMH-Mark-I** [comment]
I wished I knew how. The Chicago95 theme use to have these (and I think it still does for the GTK2 version), but more recent versions of XFCE use some sort of a glyph to generate those panel separators now. No amount of CSS hacking has been able to resolve it from my attempts.
I believe the only way that this could possibly be fixed is by making a launcher button and then making an icon that looks like the original separator and adding that to the launcher button as an icon. You'll have to make the icon in such a way that it will fit inside the panel bar without being scrunched or stretched.
It's not the best solution, but it's the only way I can think of restoring that separator style. Here's a screen shot of what I was able to accomplish with this work around. You'll notice that it isn't pixel perfect. My panel bar height is set for 27px and the fixed icon size is set for 16px.
![panel_bar](https://user-images.githubusercontent.com/28378002/196044649-45142e91-556a-464f-a67e-55cbddc13d24.png)
These are the small 16x16px separators that I created. You can adjust these to fit your preferred icon height. Generally 16x16px is what Windows 95 used on the panel bar.

Left side handle:
![handle_left_16px](https://user-images.githubusercontent.com/28378002/196044728-7cd33d73-471c-46de-abb7-23f86721df6d.png)
Right side handle:
![handle_right_16px](https://user-images.githubusercontent.com/28378002/196044729-8c1e883e-63f9-4c10-a0d6-3b60499a93ec.png)
Left side handle (thin):
![small_handle_left_16px](https://user-images.githubusercontent.com/28378002/196044730-0992ade9-d02f-4437-9dbd-17acbb7842f7.png)
Right side handle (thin):
![small_handle_right_16px](https://user-images.githubusercontent.com/28378002/196044731-79f1f9f9-08c8-4558-9858-c205ef8d2ab8.png)

I hope this helps!

**Comment by SaiTheCyclone** [comment]
This will do! Thanks!

**Comment by imkerberos** [comment]
The below code is copied from 'Redmond95'.
![image](https://github.com/user-attachments/assets/b04ff427-f2b4-4ad0-83a9-46d44ed8792e)

`
/* Hack to give the task bar a pseudo handle
Remove code after this comment to disable the fake handle image.
Since the task bar name changes based on individual panel layout, support
up to 24 different positions. */

#tasklist > box, #tasklist-1 > box, #tasklist-2 > box, #tasklist-3 > box, 
#tasklist-4 > box, #tasklist-5 > box, #tasklist-6 > box, #tasklist-7 > box, 
#tasklist-8 > box, #tasklist-9 > box, #tasklist-10 > box, #tasklist-11 > box, 
#tasklist-12 > box, #tasklist-13 > box, #tasklist-14 > box, #tasklist-15 > box, 
#tasklist-16 > box, #tasklist-17 > box, #tasklist-18 > box, #tasklist-19 > box,
#tasklist-20 > box, #tasklist-21 > box, #tasklist-22 > box, #tasklist-23 > box, 
#tasklist-24 > box {
   border-left: 11px solid;
   border-image: url("assets/handle.png");
   border-image-slice: 2 2 2 11;
}
`
