### ISSUE TITLE
Add a lightdm theme for Xubuntu's login screen

### ISSUE THREAD

**Issue by ask-compu** [grassmunk/Chicago95#269]
To complete the look

**Comment by ask-compu** [comment]
> We use to have one based on the http engine but I believe thats been discontinued. Any advice on how to recreate one?

https://www.fosslicious.com/2018/05/change-login-screen-on-xubuntu.html idk but maybe this helps?

**Comment by EMH-Mark-I** [comment]
@ask-compu It is possible to apply the Chicgo95 GTK theme to the LightDM login manager, however it won't look the spitting image of the old Windows 95 login if that is what you are looking for. Your link to fosslicious shows the steps on how to apply this. However you would have to copy the Chicago95 theme into `/usr/share/themes` , so that you can select it in the theme dropdown of the LightDM GTK+ Greeter Settings application. 

Chicago95 project use to have an accurate login manager that resembled Windows 95, but it was based on the old `lightdm-webkit-greeter` package, which is removed from current mainstream distributions package archives.

**Comment by ask-compu** [comment]
yeah but is there a new way to make the login screen fully accurate like the webkit-greeter version was?

**Comment by grassmunk** [comment]
There is not. Though you are more than welcome to try making a theme and using a more modern greeter like https://github.com/JezerM/nody-greeter
