### ISSUE TITLE
How does Chicago95 change the Firefox theme?

### ISSUE THREAD

**Issue by kevgrig** [grassmunk/Chicago95#287]
I'm facing an issue where my main Firefox profile has issues being blocked by CloudFlare DDoS protection. I cleared cookies/cache and it didn't help. Someone suggested I create a new profile using about:profiles and that works. However, it's going to be annoying to migrate everything over to the new profile. As I was wondering about what could be the difference between profiles, I see my main profile has Chicago 95 theming (e.g. the Netscape Navigator icon, different colors, etc.). My new profile didn't pick up that new theming. One hypothesis is that CloudFlare is doing some sort of fingerprinting based on the UI elements (e.g. window size) which is different with the Chicago95 theme.

So the question is: how does Chicago95 apply the Firefox theme and how can I manually apply it to my new Firefox profile to test this hypothesis?

**Comment by 266-750Balloons** [comment]
It doesn't directly modify the Firefox theme, only the GTK theme. I don't think CloudFlare would probe based on window size, as then it would block you if, say, you opened the web page while a window was not maximized for instance. I haven't had problems with the theme. That one profile is probably just set to use system color scheme in Firefox settings, while the new profile is not.

I would recommend checking if turning off any plug-ins does it, and auditing your plug-ins in general if you have any. It could be possible that A, one plugin just does something weird enough with Javascript to confuse Cloudflare, or B, one plugin has actually been using your computer as part of a botnet and Cloudfare is just doing its job correctly. I'm no expert on this, however.

I just know it's probably not Chicago95 related, and probably not relating to window size, especially since my Firefox install is even weirder than normal and gets past Cloudflare just fine.
![image](https://github.com/grassmunk/Chicago95/assets/79549730/a1746980-064f-454a-b6e7-b34a1b4293ce)
(I'm using [Redmond-Firefox](https://github.com/matthewmx86/Redmond-Firefox) with every flag known to humankind to get it working.)

**Comment by kevgrig** [comment]
Thanks! It turned out I had `general.useragent.override` set for some debugging I had been doing and forgot about it.
