### ISSUE TITLE
Black Square on Start Button

### ISSUE THREAD

**Issue by DocMAX** [grassmunk/Chicago95#32]
In Whisker Menu from last update on i get a "black square" when i press the button. Also, my Starter buttons have smaller icons now.

**Comment by EMH-Mark-I** [comment]
I can fix the Start button.

Can you share a screenshot of the smaller "Starter buttons?" I'm guessing those are the panel launchers. I do recall making some changes to them, I'll take look at it.

**Comment by EMH-Mark-I** [comment]
I added some updates. You can it a try.

**Comment by DocMAX** [comment]
The black button is gone, but the icons are still smaller than before.

![image](https://user-images.githubusercontent.com/5351323/36688699-8515b014-1b2d-11e8-8b7a-21a3270f00e6.png)

**Comment by EMH-Mark-I** [comment]
Oh OK I see what's going on. The launcher button icons are associated with the panel height. The higher the panel the larger the icon, the smaller the panel the smaller the icon. I'll take a look at the gtk2 panel.rc file.

**Comment by EMH-Mark-I** [comment]
OK so I've been looking at it.

If it means anything, the default xthickness and ythickness of the buttons is going to be set to 4px. The absolute smallest panel bar you can have with this theme at default will be 26 pixel row size. Anything below that and the icons will scale down below 16x16px which will cause improper scaling since most icon themes don't go any smaller than that.

As the panel height is increased the launcher icons will scale up. I'll add some optional steps in the guide for forcing 16x16 icons on larger panels for anyone that wants that instead of the comically oversized launcher icons that XFCE themes typically have. I'll be uploading the changes soon!

**Comment by EMH-Mark-I** [comment]
You can give it a spin now. Let me know if the icons are still microscopic!

**Comment by DocMAX** [comment]
Yes. Buttons are normal again. Well done. Thanks.

**Comment by EMH-Mark-I** [comment]
Awesome, thanks for letting me know.
