### ISSUE TITLE
Scrollbar in Icecat doesn't show

### ISSUE THREAD

**Issue by isaacdixon274** [grassmunk/Chicago95#36]
I use GNU IceCat as my main browser but for some reason the actual bar in the scrollbar doesn't show. The track for the bar and the two buttons for up and down (or left/right when the bottom scrollbar is shown) are visible, just not the actual sliding bar. I don't know if it is perhaps shown but just in the same colour as the track, rendering it invisible, or maybe it just isn't shown on the screen at all.

**Comment by EMH-Mark-I** [comment]
I haven't used IceCat before, but I'll try to take a look at it this weekend.

If possible can you upload a screenshot? It might also help if I know which distribution, OS version, and version of the IceCat browser you are using.

Thanks!

**Comment by isaacdixon274** [comment]
It might be an issue with other Firefox forks (Icecat uses an older build of Firefox), I'm not sure.

Unfortunately I'm away at the moment but as soon as I'm back (Friday) I'll upload a screenshot and my version details. I'm using Xubuntu 16.10, I believe, but I can't remember the Icecat version, sorry. I'll find out as soon as I can. Thanks

**Comment by EMH-Mark-I** [comment]
I just wanted to let you know that Ubuntu 16.10 reached end-of-life on July 20, 2017.  If you're unsure of which version of Ubuntu you are using, you can type the following command in a terminal then report it back here:

`$    lsb_release -a`

The theme repo here on GitHub tries to target systems using GTK 3.22, as seen in the requirements section of the README.md since that version is a "stable release" and is targeted for Ubuntu 18.04. I believe Ubuntu 16.10 used GTK 3.20. It gets difficult really fast if I have to start covering multiple GTK3 versions since they all have minor differences that are difficult to keep track of. :(

I'm still unsure which version of GTK IceCat requires, or if it could be forced to use GTK2? Documentation is vague, not to mention build requirements.

To see which version of GTK3 is installed on your system, you can run the following command in a terminal:

`$    dpkg -s libgtk-3-0|grep '^Version'`

I'll still try to take a look at it this weekend.

**Comment by isaacdixon274** [comment]
Sorry, I meant 16.04: `Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
`
As for the GTK version, here's the output of `dpkg -s libgtk-3-0|grep '^Version'`: `Version: 3.18.9-1ubuntu3.3`
So it turns out I'm on version 3.18, but I tried updating and I was told that the package was the newest version, there's no newer one.
I attempted to find the GTK version used by Icecat but couldn't seem to. I'll do some more research and say if I find anything.

**Comment by EMH-Mark-I** [comment]
I believe Ubuntu 16.04 is going to remain on GTK-3.18 for the rest of its life. From my experience (it could be different for others) I wouldn't recommend updating GTK3 unless you know what you're doing since there will be a lot of applications that will depend on that version.

However I do keep a repository of this theme specifically for Ubuntu 16.04 since that's the distribution I also run on.

https://github.com/EMH-Mark-I/Chicago95-Custom-XUbuntu-16.04-

Give that a try and see how it works for you. There is one caveat to it though and that's to deal with the GNOME Client Side Decorations for some GTK3 applications. I restyled them because of issues with non-compositing  environments, so it will require a program called gtk3-nocsd to force the window manager title-bar onto those applications. You can still use it without gtk3-nocsd, but any GNOME application that's using client side decorated title bars will look out of place FYI.

I have the steps on installing all of that in the INSTALL.md file over there, so let me know if you have issues with it.

**Comment by isaacdixon274** [comment]
That's working fine for me now. I didn't realise there was another one specific to Ubuntu 16.04, that's my fault, sorry.
Thank you for your help :)
