### ISSUE TITLE
Desktop icons in XFCE are semi-transparent

### ISSUE THREAD

**Issue by vitacell** [grassmunk/Chicago95#40]
Hi, maybe year ago, I got that issue when I was on Arch, after updating it. Today I use Void, and I installed XFCE again, and got the same issue in XFCE (icons are fine in LXDE). This problem happens in XFCE and with icons called "Chicago95" and "Chicago95-tux" only. All other icons are fine. So an year ago I had working fine "Chicago95" desktop icons. The compressed files and folders icons, have some strange colors. Something is wrong with Chicago95 icons and XFCE, I tryed to change to other gtk theme, and does not fix the problem. Maybe it is because XFCE devs are porting good gtk2 things to crappy gtk3?

EDIT: icons are fine in Ubuntu18.04+XFCE, but the problem are rolling release distros with XFCE.

![captura de pantalla_2018-09-23_21-35-43](https://user-images.githubusercontent.com/18006295/45932193-3f0b2880-bf68-11e8-87e3-a6e6c5f0e8d4.png)

![captura de pantalla_2018-09-23_21-35-43](https://user-images.githubusercontent.com/18006295/45932280-572f7780-bf69-11e8-8a10-914ce856a47e.png)

**Comment by grassmunk** [comment]
It's likely an issue with both the way I made really large icons (SVGs) and your screen resolution. I'm honestly not sure what do to here. 

The way the SVGs were created was by making a one to one map SVG file. What this means is that it's basically a bunch of tiny squares in the SVG file. As the image gets larger i guess the gaps between the 'pixels' in the SVGs get big enough to cause them to be visible. 

@EMH-Mark-I any thoughts?

**Comment by EMH-Mark-I** [comment]
@grassmunk 

I was looking at this last week. As you were saying, it is with the SVG icon because It happens once the icons are expanded enough to move over into the "scaled" icons theme. There were a few that looked fine, but those were in the 48x48 theme and didn't have a scaled SVG icon (like the missing icon or disk drives icons I believe.)

I'm not familiar enough with SVG icons, but I wonder if there's a way to convert the PNG icons into SVG to where they wouldn't do this? I looked at the elementary icon theme and things were fine there.

**Comment by vitacell** [comment]
Guy, thanks for your answers, now with your answers I can fix that problem by just changing desktop icon size. The 48 size looks the correct one.

**Comment by vitacell** [comment]
> Thats great! I'm still going to leave this issue open because its a known issue that should be changed.

Yeah, ok. That thing only happens with Chicago-95 icons.

**Comment by grassmunk** [comment]
See enhacement: https://github.com/grassmunk/Chicago95/issues/78
