### ISSUE TITLE
Make Chicago95 Lubuntu please

### ISSUE THREAD

**Issue by zlietapki** [grassmunk/Chicago95#5]
Xubuntu and Lubuntu is almost the same. So would you be so kind and port your project for Lubuntu usage?
Thanks for your work. It looks great!

**Comment by googkhan** [comment]
most of items usable in lubuntu

**Comment by DonutDeflector** [comment]
It seems like this project may be dead. Perhaps a fork will show up sometime soon.

**Comment by grassmunk** [comment]
It's no dead perse, just don't have time to focus on this. I incorporated a bunch of changes today but really don't have time to work on the project myself. I'll accept push requests though. 

As for Lubuntu, do you know what exactly I'd need to change to make it work?

**Comment by DonutDeflector** [comment]
Alright, it seemed like activity stalled for quite a while. That's ok. :P

**Comment by jacobpoo** [comment]
@grassmunk from what I remember, an openbox theme is a necessity

**Comment by vitacell** [comment]
@zlietapki just install "xfwm4" and you can use Chicago95 window decoration.

**Comment by EMH-Mark-I** [comment]
Question; Didn't Lubuntu move their desktop to LXQT? So far this is a GTK these, I don't know how to port that to QT! D:

**Comment by Abdullah-95** [comment]
I just installed your excellent theme and love it :D but I have a problem I cannot solve since ever having never done this kind of install before :o some screens are missing the grey backgrounds, like the login screen and software manager is almost unreadable etc, and some highlights don't work, are there any fixes for this? what can I do to sort out this problem?

Regards, Abdullah

**Comment by vitacell** [comment]
> I just installed your excellent theme and love it :D but I have a problem I cannot solve since ever having never done this kind of install before :o some screens are missing the grey backgrounds, like the login screen and software manager is almost unreadable etc, and some highlights don't work, are there any fixes for this? what can I do to sort out this problem?
> 
> Regards, Abdullah

First, the seers of this projects are on vacations. Probably nobody knows what GNU/Linux distribution you are using, every distro has his own versions of GTK2, and GTK3, and GTK3 is much more problematic, because it has no backward compatibility. And newer versions of Xfce4 are releasing built with GTK3 which is absolutely incompatible with GTK2. Try this fork Xfce4-gtk2:

https://github.com/EMH-Mark-I/Chicago95-Custom-XUbuntu-16.04-

**Comment by grassmunk** [comment]
We're not on vacation, we literally just pushed updates last week. We've stated we only support XFCE and are experimenting with KDE. @Abdullah-95 if you have specific problem with this theme in XFCE4, specifically Xubuntu, tell us which programs you're running specifically that are causing the problems in XFCE in a new issue. When submitting specific GTK application issues please run the application from the command line and include screenshots. 

As for the logon screen we include both a lightdm theme and a SDDM theme which you can find instructions for here (https://github.com/grassmunk/Chicago95/blob/master/Lightdm/Chicago95/README.md) and here (https://github.com/grassmunk/Chicago95#kde-support-experimental)
