### ISSUE TITLE
Chicago95 Greeter

### ISSUE THREAD

**Issue by 1337god** [grassmunk/Chicago95#50]
I have installed both lightdm and lightdm-webkit-greeter changed all the settings and copied Chicago95 folder to the lightdm webkit themes folder.
But whenever I restart I get a black screen, I am using Ubuntu 18.04

**Comment by EMH-Mark-I** [comment]
Sorry about that.

Could you tell me which "Chicago95" folder you copied into the `/usr/share/lightdm-webkit/themes/` folder? I just noticed that it might be easy to confuse which "Chicago95" folder should be copied.

For the lightdm webkit theme, copy the "Chicago95" folder from, `Chicago95-master/Lightdm/` not `Chicago95-master/Theme/`

Also make sure in the `/etc/lightdm/lightdm-webkit-greeter.conf` file that the default settings are all commented out and just add: 
```
[greeter]
webkit-theme=Chicago95
```
At some point I need to revise the instructions a little because I often make a mistake when setting this up myself.

**Comment by 1337god** [comment]
Yes, I have checked I have copied the correct folder.

**Comment by EMH-Mark-I** [comment]
Can you tell me which distribution you are running and the version number?

`lsb_release -a`

Also can you run the following command and then paste the output to here?

`cat /etc/lightdm/lightdm.conf /etc/lightdm/lightdm-webkit-greeter.conf && ls -l /usr/share/lightdm-webkit/themes/Chicago95`

**Comment by 1337god** [comment]
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
C:\home\lain>

**Comment by 1337god** [comment]
`[SeatDefaults]
logind-check-graphical=true
greeter-session=lightdm-greeter
user-session=xfce
#
# background = Background file to use, either an image path or a color (e.g. #772953)
# theme-name = GTK+ theme to use
# font-name = Font to use
# xft-antialias = Whether to antialias Xft fonts (true or false)
# xft-dpi = Resolution for Xft in dots per inch (e.g. 96)
# xft-hintstyle = What degree of hinting to use (hintnone, hintslight, hintmedium, or hintfull)
# xft-rgba = Type of subpixel antialiasing (none, rgb, bgr, vrgb or vbgr)
#
[greeter]
background=/usr/share/backgrounds/warty-final-ubuntu.png
theme-name=Ambiance
webkit-theme=Chicago95
font-name=Ubuntu 11
xft-antialias=true
xft-dpi=96
xft-hintstyle=slight
xft-rgba=rgb
/usr/share/lightdm-webkit/themes/Chicago95:
total 36
drwxr-xr-x 5 root root 4096 nov 20 23:55 .
drwxr-xr-x 5 root root 4096 nov 21 10:55 ..
drwxr-xr-x 2 root root 4096 nov 20 23:55 css
drwxr-xr-x 2 root root 4096 nov 20 23:55 img
-rwxr-xr-x 1 root root 1565 nov 20 23:55 index.html
-rwxr-xr-x 1 root root  104 nov 20 23:55 index.theme
drwxr-xr-x 2 root root 4096 nov 20 23:55 js
-rw-r--r-- 1 root root 1085 nov 20 23:55 LICENSE
-rw-r--r-- 1 root root 1842 nov 20 23:55 README.md

/usr/share/lightdm-webkit/themes/Chicago95/css:
total 24
drwxr-xr-x 2 root root 4096 nov 20 23:55 .
drwxr-xr-x 5 root root 4096 nov 20 23:55 ..
-rwxr-xr-x 1 root root  130 nov 20 23:55 clearfix.css
-rwxr-xr-x 1 root root 3779 nov 20 23:55 layout.css
-rwxr-xr-x 1 root root 7589 nov 20 23:55 normalize.css

/usr/share/lightdm-webkit/themes/Chicago95/img:
total 16
drwxr-xr-x 2 root root 4096 nov 20 23:55 .
drwxr-xr-x 5 root root 4096 nov 20 23:55 ..
-rw-r--r-- 1 root root  323 nov 20 23:55 close_normal.png
-rw-r--r-- 1 root root  547 nov 20 23:55 start.png

/usr/share/lightdm-webkit/themes/Chicago95/js:
total 24
drwxr-xr-x 2 root root 4096 nov 20 23:55 .
drwxr-xr-x 5 root root 4096 nov 20 23:55 ..
-rwxr-xr-x 1 root root 7231 nov 20 23:55 main.js`

**Comment by EMH-Mark-I** [comment]
Well it all looks correct, aside from the lightdm.conf file using `greeter-session=lightdm-greeter` instead of `greeter-session=lightdm-webkit-greeter`; but I'm guessing you did that to fix the black screen issue.

Anyhow, I can't think of what else may be causing this. If you have the time, we could try to take a look at the output of lightdm while using the lightdm-webkit-greeter theme. 

To do this you'll have to log out, switch over to a different TTY terminal (ctrl+alt+F5); run `sudo systemctl stop lightdm.service` this will just close the lightdm process that's currently running. Next run `sudo lightdm -d --test-mode > output.txt 2>&1` and this will send the output into a file on your home directory.

Your display will switch back to the login manager. You can sign in then sign back out to test it, if it's working. Then switch back to your TTY (ctrl+alt+F5) and press ctrl+c to close the process. After all of that you can change the lightdm.conf file back to the standard `greeter-session=lightdm-greeter` and restart the lightdm service with `sudo systemctl restart lightdm.service` to return things back to normal.

**Comment by grassmunk** [comment]
There's an easier way to test LightDM: https://wiki.debian.org/LightDM#Testing I would try that first.

**Comment by 1337god** [comment]
> There's an easier way to test LightDM: https://wiki.debian.org/LightDM#Testing I would try that first.

I did the test and it works fine, but when selecting lightdm-webkit-greeter as greeter-session and I restart the computer it just goes completely black.

**Comment by grassmunk** [comment]
Did this get fixed? I just accepted a pull request to make a change to the greeter. If it still doesn't work please reopen the ticket.
