### ISSUE TITLE
XFCE Panel text color is white.

### ISSUE THREAD

**Issue by pushqrdx** [grassmunk/Chicago95#51]
Hey, i really like how good this looks but i have a little issue, all text in the Panel is white. Can you help me with that? 

I am running latest Xubuntu 18.10.

**Comment by EMH-Mark-I** [comment]
So far the GTK3 portion of the theme only targets GTK3.22 which is the version used on XUbuntu 18.04 since that version of GTK is the long-term stable version. I won't be able to port it to GTK 3.30 which is the version used on Ubuntu 18.10, but if someone else could that would be awesome!

You can run the following in a terminal to get the version of GTK3 on your system:

`dpkg -s libgtk-3-0|grep '^Version'`

I wouldn't advise attempting to downgrade GTK3 on your system either since it's a dependent for essentially every GTK3 application on your system on that distribution.

Now for the GTK2 portion, that should actually still work fine. I can see where some issues might occur with the mix match in XFCE's transition from GTK2 to GTK3.

I hope that explains it! I can set the issue as an "enhancement" request for anyone that wants to take it up.

**Comment by pushqrdx** [comment]
@EMH-Mark-I Well, Thanks a lot for your response. I am willing to fiddle with that it's just that i am very new to linux as a whole so i am still figuring my way around my gtk version appears to be 3.24.1-1ubuntu2 which isn't that different from 3.22 so it's weird that there's a miss-match. Could you, please, guide me a little bit on that?

**Comment by EMH-Mark-I** [comment]
I've been using the inspector tool, I believe it comes with the `libgtk-3-dev` package which can be installed from apt. Another one to use for example is the `gtk-3-examples` package; also can be installed from apt. It contains GTK3 demo applications (gtk3-demo, gtk3-demo-application, and gtk3-widget-factory.)

For GTK2 it's been more of a guessing game for me. You can get examples from other GTK2 themes and you can use the widget factory tool (awf-gtk2 and awf-gtk3) [from Launchpad](https://launchpad.net/~flexiondotorg/+archive/ubuntu/awf) to get some decent feed back. No inspector tools for GTK2 that I know of, but a lot of GTK2 is based on static images so you can just work on it from out of GIMP.

Through my findings it's kinda tough to make a skeuomorphic style theme on GTK3 without resorting to hackery. You'll notice a lot of static images being used for the GTK3 theme as a result. A lot of newer applications favour zero-border flat styles with heavy padding and hard coded themeing that overrides user themes.

Good luck!

**Comment by EMH-Mark-I** [comment]
Oh wow this actually looks usable on XUbuntu 18.10. (In case you didn't know, I haven't even touched 18.10 yet) I do see some minor things that are off. Right off the bat I notice the window buttons on the panelbar are GTK3 now, reason being the text is white instead of black. In XUbuntu 18.04 the Window Buttons plugin is GTK2. It's actually a pretty simple fix.

In a terminal insert the follow:

`echo "#Xfce4PanelWindow label {color: black;}" >> ~/.config/gtk-3.0/gtk.css`

Log out then log back in. If you ever decide to change the theme don't forget to remove that gtk.css file in /home/$USER/.config/gtk-3.0/gtk.css. It's an override that will affect other themes.

**Comment by EMH-Mark-I** [comment]
Had to make a quick edit to the command. I left out the button node. Just letting you know in case you read these from email like me...

**Comment by pushqrdx** [comment]
@EMH-Mark-I  After fiddling around for a while, for some strange reason, overriding the color in `/.config/gtk-3.0/gtk.css` didn't work. The panel foreground color stayed white. Then, I discovered that `.themes/Chicago95/gtk-3.0/apps/xfce.css` had 
```
.xfce4-panel button {
    ...
    color: @panel_fg_color;
    ...
}
```
Changing `@panel_fg_color` to `@theme_text_color` and running `xfce4-panel -r` in terminal to quickly restart the panel immedietly fixed the issue.

**Comment by EMH-Mark-I** [comment]
If you can, or have the time, try it out now.
