### ISSUE TITLE
Conversion of Chicago95 to a Windows 98/Windows 2000 theme?

### ISSUE THREAD

**Issue by mknepper** [grassmunk/Chicago95#55]
I didn't see where to put this, so I was curious if it could be a possibility. I'm not sure how I can help, but I will definitely do so. The only other available Windows 98/9x theme is kind of broken since it hasn't been updated in like, a year. Thoughts?

**Comment by EMH-Mark-I** [comment]
It probably wouldn't be too hard. About the only changes between them and Windows 95 was the base grey colour, menu bar item activation styling, and the window manager title-bar.

I don't actually know how to make the title-bar use a gradient as seen in 98 since the theme is using the GTK2 pixmap engine for rendering images. There might be a GTK2 engine that can support a horizontal colour gradient, but I haven't seen it.

**Comment by mknepper** [comment]
Hmm. I'll look into that. Some themes seem to be able to do it, but I'm unsure how they're accomplishing it. Seems this theme has vertical gradients in the title bar:

https://www.xfce-look.org/p/1277683/

**Comment by grassmunk** [comment]
The challenge is the way the XPMs are built there's no easy way to do the titlebar gradients:

![image](https://user-images.githubusercontent.com/3452173/60197497-55def400-97f4-11e9-9940-29d6b31f0889.png)

More info: https://wiki.xfce.org/howto/xfwm4_theme
