### ISSUE TITLE
Window Buttons are flat, even when "show flat buttons" is unchecked

### ISSUE THREAD

**Issue by 301views** [grassmunk/Chicago95#67]
This was after updating from Xubuntu 18.04 to 18.10, then to 19.04.
![flat buttons](https://user-images.githubusercontent.com/18691934/56474214-bd6b7280-6444-11e9-94ef-d427e9c93099.png)

**Comment by EMH-Mark-I** [comment]
I'm working on a port for GTK3.24 of the theme. I'll upload it soon. It should fix the panel buttons, as well as the font colour. I'm currently stuck on the GTK2 Notification area plugin, which for some reason is moving the icons out of view.

**Comment by EMH-Mark-I** [comment]
Just writing out the following for documentation:

The new GTK3 XFCE panelbar tasklist buttons will require a work around for the GTK3.24 port. 

Styling the button element itself works and is responsive to the flat button toggle, however this comes with a caveat for Chicago95. The tasklist toggle buttons will fill the entire area of the panelbar, leaving no margins.

Since the direction of the theme is to imitate Windows 95, this appearance would go against that. Applying margins to the button element works and will achieve the proper visual effect, but this will reduce the interactive area of the tasklist button, making it require accurate precision to activate; this presents a usability problem.

So for a work around that won't impact usability, I can style the box element inside of the toggle button element and apply the margins there. This will achieve the proper visual effect and without any impacts to usability, however this cause the flat button toggle for the tasklist settings to become useless. I'm willing to accept this and will include it for the port.

**Comment by vitacell** [comment]
GNOME keep breaking thing as always. GTK2 is better thing to stay with.

**Comment by EMH-Mark-I** [comment]
Well, I wouldn't think of that in this case. So far setting up the port has been smooth compared to the transition from GTK3.18 to 3.22 which required renaming a lot of elements and pulling out deprecated styling and basically just redoing everything.

Since Chicago95 is a theme made in the traditional skeuomorphic styling, this is going against the direction of the toolkit and many applications too which favour a flat heavily padded style with minimal design.

I think the real hassle was having to handle the awkward mix of GTK2 and 3 plugins on the XFCE panel in such a way that it doesn't look broke and still achieves the visual theme that's being aimed for. With the new release of the XFCE desktop, a lot of that headaches goes away! Launcher button icons, status icons, and notification icons finally scale properly when the panelbar size is increased; provided that the icon theme is scalable.

There are a few new GTK3 applications and plugins now included that I've got styled properly; Thunar, xfdesktop, xfce4-panel, and panel plugins (although probably not all of them, but can be dealt with as people come by them.) I'm still testing around with it before I commit my changes. There will still be support for GTK3.18 too, I just wanted to include 3.24 as well since I'm receiving emails and noticing tickets here from people on the latest release of XUbuntu and Manjaro submitting issues.

**Comment by EMH-Mark-I** [comment]
Give it a try now.
