### ISSUE TITLE
Some programms theming is broken

### ISSUE THREAD

**Issue by vitacell** [grassmunk/Chicago95#84]
![Captura de pantalla_2019-07-30_15-55-37](https://user-images.githubusercontent.com/18006295/62135775-16b82d00-b2e3-11e9-96bb-70f0deb22166.png)
![Captura de pantalla_2019-07-30_16-01-12](https://user-images.githubusercontent.com/18006295/62135892-52eb8d80-b2e3-11e9-8abd-c703189caa40.png)
![Captura de pantalla_2019-07-30_17-15-01](https://user-images.githubusercontent.com/18006295/62141927-ae227d80-b2ed-11e9-840f-4252d4fd16dd.png)
![Captura de pantalla_2019-07-30_17-15-26](https://user-images.githubusercontent.com/18006295/62141928-ae227d80-b2ed-11e9-992d-7c5b8e312604.png)
![Captura de pantalla_2019-07-30_17-14-43](https://user-images.githubusercontent.com/18006295/62141929-aebb1400-b2ed-11e9-9236-215df418b2e1.png)

This bad theming did not happen with older releases, but even in older one something is happening with icon's backgrounds (those looks white instead of transparent).

Is it a good idea split Chicago95 into two versions? one for gtk2 and other one for gtk3.

**Comment by EMH-Mark-I** [comment]
What operating system and release version are you using? If it's Debian based, you can also run the following to output the version of GTK3 that's installed on your system which would be helpful to know.

$ dpkg -s libgtk-3-0|grep '^Version'

So far the applications you are showing to have issues are GTK3 based. The theme supports both GTK3.22 and GTK3.24. If the applications require for example, GTK3.18, then you can use [my fork of Chicago95](https://github.com/EMH-Mark-I/Chicago95-Custom-XUbuntu-16.04-) for Xenial Xerus (Ubuntu 16.04) desktops.

Can you list the contents of the version of Chicago95 that's not working:

    ls -l ~/.themes/Chicago95/
    ls -l ~/.themes/Chicago95/gtk-3.0/
    ls -l ~/.themes/Chicago95/gtk-3.24/

**Comment by vitacell** [comment]
I am using Salix, which is the same as Slackware14.2. And yes, it is gtk3.18. I tryed your fork and it is working fine, thanks. But, is it normal that this Thunar's toolbar is bigger size?
![Captura de pantalla_2019-07-31_03-38-10](https://user-images.githubusercontent.com/18006295/62177374-fcaf3680-b344-11e9-94fa-ad86dcb06ce8.png)
![Captura de pantalla_2019-07-31_03-38-29](https://user-images.githubusercontent.com/18006295/62177376-fe78fa00-b344-11e9-89ea-9b24caad38f7.png)

**Comment by EMH-Mark-I** [comment]
Oh, yeah that's what it use to look like before I reduced the widget sizes for the theme here. I haven't updated the forked version of the theme for quite some time. I can update the fork to match. Keep in mind some applications (namely GTK3) comparatively won't look the same with the version of the theme here.

I just updated that fork. I recommend reading the install instructions there. Due to some issues with client side decorations on GTK3.18, I wasn't ever able to get them working correctly like here so then recommended using gtk3-nocsd to disable them. I'm not sure how well the steps for install gtk3-nocsd will work for you since you're on Salix however.

**Comment by EMH-Mark-I** [comment]
I've also updated the icon theme to match with the icon theme here. This should resolve your issue #83.

**Comment by vitacell** [comment]
> Oh, yeah that's what it use to look like before I reduced the widget sizes for the theme here. I haven't updated the forked version of the theme for quite some time. I can update the fork to match. Keep in mind some applications (namely GTK3) comparatively won't look the same with the version of the theme here.
> 
> I just updated that fork. I recommend reading the install instructions there. Due to some issues with client side decorations on GTK3.18, I wasn't ever able to get them working correctly like here so then recommended using gtk3-nocsd to disable them. I'm not sure how well the steps for install gtk3-nocsd will work for you since you're on Salix however.

Looks like I have "gtk3-nocsd" already installed by default in Salix. (I really hate gtk3, and anything related with it).



> I've also updated the icon theme to match with the icon theme here. This should resolve your issue #83.

No, huge PulseAudio's icon is still present, and I don't know how to fix it. And do you know why (with any gtk/icon theme) my steam icon is never appearing? (it shows like a missing icon).
![Captura de pantalla_2019-07-31_12-53-08](https://user-images.githubusercontent.com/18006295/62206644-905b2400-b392-11e9-8039-d3c422331542.png)

**Comment by EMH-Mark-I** [comment]
Well now I'm a little perplexed. I had updated the gtk.css override file because I didn't think it necessary to include the padding settings for the PA icon since I copied over the icon theme. I guess that I forgot that this version of XFCE doesn't play nice with icon sizes on the panelbar.

I updated the override file seen in `misc/gtk.css` for the forked version of the theme. You can add this manually though.

  printf "#pulseaudio-button { padding: 6px 6px; }\n#xfce4-power-manager-plugin { padding: 6px 6px; }\n" >> ~/.config/gtk-3.0/gtk.css

Let me know if this works!    

As for the Steam icon, does it return if you change the icon theme to one of the defaults that came with your system? I believe this can occur if Steam is installed through one of the new package container formats, but I could be wrong about that.

----

#83

**Comment by vitacell** [comment]
> Well now I'm a little perplexed. I had updated the gtk.css override file because I didn't think it necessary to include the padding settings for the PA icon since I copied over the icon theme. I guess that I forgot that this version of XFCE doesn't play nice with icon sizes on the panelbar.
> 
> I updated the override file seen in `misc/gtk.css` for the forked version of the theme. You can add this manually though.
> 
> ```
> printf "#pulseaudio-button { padding: 6px 6px; }\n#xfce4-power-manager-plugin { padding: 6px 6px; }\n" >> ~/.config/gtk-3.0/gtk.css
> ```
> 
> Let me know if this works!
> 
> As for the Steam icon, does it return if you change the icon theme to one of the defaults that came with your system? I believe this can occur if Steam is installed through one of the new package container formats, but I could be wrong about that.
> 
> #83
This is my code, well, I tryed removing everything but pulseaudio code. It doesn't work with any combination:
http://dpaste.com/0RYXP2Y

No, it always displays a missing-icon icon with any icon theme. No, I did not install it with Flatpak, Snap or AppImage.

**Comment by EMH-Mark-I** [comment]
Great, the PA icon issue should be resolved then! Just to note - the modifications to gtk.css won't ever take effect until the xfce4-panel bar process is reset. You can do this by rebooting (as you did) or by running in a terminal `xfce4-panel -r`.

I do know that the Steam client does work with the legacy Notification Area plugin. Since the Steam status icon isn't working with other icon themes, then there may be something wrong with Steam or your system is missing the libappindicator libraries, or something else. I don't have experience with Slack based operating systems, however the package name on Debian is libappindicator1 and libappindicator3-1.

**Comment by vitacell** [comment]
> Well now I'm a little perplexed. I had updated the gtk.css override file because I didn't think it necessary to include the padding settings for the PA icon since I copied over the icon theme. I guess that I forgot that this version of XFCE doesn't play nice with icon sizes on the panelbar.
> 
> I updated the override file seen in `misc/gtk.css` for the forked version of the theme. You can add this manually though.
> 
> ```
> printf "#pulseaudio-button { padding: 6px 6px; }\n#xfce4-power-manager-plugin { padding: 6px 6px; }\n" >> ~/.config/gtk-3.0/gtk.css
> ```
> 
> Let me know if this works!
> 
> As for the Steam icon, does it return if you change the icon theme to one of the defaults that came with your system? I believe this can occur if Steam is installed through one of the new package container formats, but I could be wrong about that.
> 
> #83
